version: "3.0"

services:
  fsm:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./images:/app/images
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"